# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0608423b49b15e234729f2cb6e1bf57c3c3dae13f7717f3d1d648685de57b711ca1ad758e1b917dad23459882e9cc649b3e8fd320061497f73de064a10fbaab

test:
  secret_key_base: 217918b800959d75a350cf519c462a732216cbced2a1872e7be7cda5b386ffd9c3b78f19d01154bbb38794d95d3aa822b70fc22c812d78e2b0cb8bca7eaa22a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
